### ISSUE TITLE
could not able to install

### ISSUE THREAD

**Issue by exp-nazeem** [sgpatil/orientdb#2]
The requested package sgpatil/orientdb could not be found in any version, there may be a typo in the package name

**Comment by ccunnin297** [comment]
Try moving the directory into [project name]/vendor so it looks like this:
[project name]/vendor/Sgpatil/Orientdb

This worked for me, but now I'm having trouble when doing the composer update. I'm getting the following message:

Failed to download sgpatil/orientdb-php from dist: '/Users/[me]/workspace/[project]/vendor/sgpatil/orientdb-php/3524afa537ddac2386192cba5075f950' is not a zip archive.

**Comment by sgpatil** [comment]
Sorry but the package is under development. There was some issue with composer. I have resolved it. Now you can install it. In this release you are able to connect with database and create a class. I have written migration for creating class but not added yet. I will upload it in this week.

**Comment by sgpatil** [comment]
Now it is ready to install and migrations also working.
